####################################################################################################
#                _____ _  ____ _                            ____ _                 _               #
#               | ____| |/ ___| |__   __ _ _ __ ___   ___  / ___| | ___  _   _  __| |              #
#               |  _| | | |   | '_ \ / _` | '_ ` _ \ / _ \| |   | |/ _ \| | | |/ _` |              #
#               | |___| | |___| | | | (_| | | | | | | (_) | |___| | (_) | |_| | (_| |              #
#               |_____|_|\____|_| |_|\__,_|_| |_| |_|\___/ \____|_|\___/ \__,_|\__,_|              #
#                                                                                                  #
####################################################################################################
#          Web > https://www.elchamo.cloud / Github > https://www.github.com/elchamocloud          #
####################################################################################################

name: Notification from Github Pull Request Closure to Google Chat

on:
  pull_request:
    types: [closed]

jobs:
  call-workflow:
    uses: elchamocloud/github-actions-templates/.github/workflows/template-github-pull-request-closure-google-chat-notification.yml@main
    secrets:
      GCHAT_WEBHOOK: ${{ secrets.GCHAT_WEBHOOK }}